/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
class Complejo(
    private var real: Double=0.0,
    private var imag: Double=0.0) {

    fun inicializar(real: Double,imag: Double) {
        this.real=real
        this.imag=imag
    }
    fun mostrar() {
        println(this.toString())
    }
    override fun toString(): String{
        return "(${real},${imag})"
    }
    fun sumar(otro: Complejo): Complejo{
        return Complejo(
            real+otro.real,
            imag+otro.imag
        )
    }
    fun multiplicar(otro:Complejo):Complejo{
        return Complejo(
            real*otro.real-imag*otro.imag,
            real*otro.imag+imag*otro.real
        )
    }
    fun dividir(otro: Complejo): Complejo {
        val denominador=otro.real*otro.real+otro.imag*otro.imag
        require(denominador !=0.0) {"No se puede dividir por 0"}
        return Complejo(
            (real*otro.real+imag*otro.imag)/denominador,
            (imag*otro.real-real*otro.imag)/denominador
        )
    }
}

fun main() {
    var complejo: Complejo
    complejo = Complejo()
    complejo.inicializar(3.0,4.0)
    println("mi número complejo es ${complejo.toString()}")
    var c2: Complejo=Complejo(1.0, 2.0)
    var c3: Complejo
    c3=complejo.sumar(c2)
    c3.mostrar()
    c3=complejo.multiplicar(c2)
    c3.mostrar()
    c3=complejo.dividir(c2)
    c3.mostrar()
}